//
//  CharactersPresenter.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 2/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharactersPresentationLogic {
    func setupView()
    func presentCharacters()
}

class CharactersPresenter: CharactersPresentationLogic {
    
    weak var viewController: CharactersDisplayLogic?
    
    func setupView() {
        
        // 1. create viewModel
        let viewModel = Characters.SetupView.ViewModel(title: "characters.title".localized)
        
        // 2. display data
        viewController?.setupView(viewModel: viewModel)
    }
    
    func presentCharacters() {
        viewController?.displayCharacters()
    }
}
