//
//  CharactersPresenter.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 2/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharactersPresentationLogic {
    func setupView(response: Characters.SetupView.Response)
    func presentCharacters()
    func presentDetails(response: Characters.DidSelectedItem.Response)
    func presentEmptyView()
    func displayLoading(_ show: Bool)
}

class CharactersPresenter: CharactersPresentationLogic {

    weak var viewController: CharactersDisplayLogic?
    
    func setupView(response: Characters.SetupView.Response) {
        
        // 1. create viewModel
        let viewModel = Characters.SetupView.ViewModel(title: response.title)
        
        // 2. display data
        viewController?.setupView(viewModel: viewModel)
    }
    
    func presentCharacters() {
        viewController?.displayCharacters()
    }
    
    func presentDetails(response: Characters.DidSelectedItem.Response) {
        
        
        // 1. create viewModel
        let viewModel = Characters.DidSelectedItem.ViewModel(actor: response.actor)
        
        // 2. display data
        viewController?.displayDetailsOfCharacter(viewModel: viewModel)
    }
    
    func presentEmptyView() {
        viewController?.displayEmptyState()
    }
    
    func displayLoading(_ show: Bool) {
        
        if let vc = viewController as? BaseViewController {
            vc.displayLoading(show)
        }
    }
}
