//
//  CharactersWorker.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 2/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CharactersWorker {
    
    /// method that downloads characters data for a specific serie from API Repository
    /// - Parameter completion: block
    func getCharacters(for serie: Serie, completion: @escaping([Actor]?, String?) -> Void) {
        
        // LETS and VARS
        let charactersRepository = CharacterRepository()
        
        // Get Characters of an especific serie
        charactersRepository.getCharacters(for: serie) { (actors) in
            print(actors)
            completion(actors, nil)
        }
    }
}
