//
//  CharactersRouter.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 2/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CharactersRoutingLogic {
    func routerToDetails(segue: UIStoryboardSegue?)
}

protocol CharactersDataPassing {
    var dataStore: CharactersDataStore? { get }
}

class CharactersRouter: NSObject, CharactersRoutingLogic, CharactersDataPassing {
    
    weak var viewController: CharactersViewController?
    var dataStore: CharactersDataStore?
    
    // MARK: CharactersRoutingLogic
    
    func routerToDetails(segue: UIStoryboardSegue?) {
        let storyboard = UIStoryboard(name: Constants.Storyboard.details, bundle: nil)
        
        if let segue = segue, let destinationVC = segue.destination as? DetailsViewController {
            var destinationDS = destinationVC.router?.dataStore
            passDataToDetails(source: dataStore, destination: &destinationDS)
        } else if let destinationVC = storyboard.instantiateInitialViewController() as? DetailsViewController {
            var destinationDS = destinationVC.router?.dataStore
            passDataToDetails(source: dataStore, destination: &destinationDS)
            navigateToDetails(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    fileprivate func navigateToDetails(source: CharactersViewController, destination: DetailsViewController) {
        ui {
            source.present(destination, animated: true)
        }
    }
    
    // MARK: Passing data
    
    fileprivate func passDataToDetails(source: CharactersDataStore?, destination: inout DetailsDataStore?) {
        destination?.character = source?.selectedCharacter
    }
}
