//
//  SeriesWorkerTests.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 3/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONMarvelapp
import XCTest

class SeriesWorkerTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: SeriesWorker!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupSeriesWorker()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupSeriesWorker() {
    sut = SeriesWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
}
