//
//  DetailsPresenterTests.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 4/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONMarvelapp
import XCTest

class DetailsPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: DetailsPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupDetailsPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupDetailsPresenter() {
        sut = DetailsPresenter()
    }
    
    // MARK: Test doubles
    
    class DetailsDisplayLogicSpy: DetailsDisplayLogic {
        
        var setupViewCalled = false
        
        func setupView(viewModel: Details.SetupView.ViewModel) {
            setupViewCalled = true
        }
    }
    
    // MARK: Tests
    
    func testSetupView() {
        // Given
        let spy = DetailsDisplayLogicSpy()
        sut.viewController = spy
        
        // When
        sut.setupView(response: .init())
        
        // Then
        XCTAssertTrue(spy.setupViewCalled, "setupView should ask the view controller to setupViewCalled")
    }
}
