//
//  DetailsViewControllerTests.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 4/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONMarvelapp
import XCTest

class DetailsViewControllerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: DetailsViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupDetailsViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupDetailsViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Details", bundle: bundle)
        sut = storyboard.instantiateInitialViewController() as? DetailsViewController
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    class DetailsBusinessLogicSpy: DetailsBusinessLogic {
        
        var setupViewCalled = false
        var getSeriesCountCalled = false
        var getComicsCountCalled = false
        var getSectionsCountCalled = false
        var getDataCellForCalled = false
        
        func setupView() {
            setupViewCalled = true
        }
        
        func getSeriesCount() -> Int {
            getSeriesCountCalled = true
            return 0
        }
        
        func getComicsCount() -> Int {
            getComicsCountCalled = true
            return 0
        }
        
        func getSectionsCount() -> Int {
            getSectionsCountCalled = true
            return 0
        }
        
        func getDataCellFor(index: Int, section: Int) -> Details.Models.DetailCellModel {
            getDataCellForCalled = true
            return .init()
        }
        
    }
    
    // MARK: Tests
    
//    func testShouldDoSomethingWhenViewIsLoaded() {
//        // Given
//        let spy = DetailsBusinessLogicSpy()
//        sut.interactor = spy
//
//        // When
//        loadView()
//
//        // Then
//        XCTAssertTrue(spy.doSomethingCalled, "viewDidLoad() should ask the interactor to do something")
//    }
//
//    func testDisplaySomething() {
//        // Given
//        let viewModel = Details.Something.ViewModel()
//
//        // When
//        loadView()
//        sut.displaySomething(viewModel: viewModel)
//
//        // Then
//        //XCTAssertEqual(sut.nameTextField.text, "", "displaySomething(viewModel:) should update the name text field")
//    }
}
