//
//  MainWorker.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 1/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainWorker {
    
    func getInitialData(completion: @escaping([Serie]?, String?) -> Void) {
        
        // LETS and VARS
        var mSeries: [Serie]?
        let serieRepository = SerieRepository()
        let dispatchGroup = DispatchGroup()
        
        // Get Series
        dispatchGroup.enter()
        serieRepository.getSeries() { series in
            print(series)
            mSeries = series
            dispatchGroup.leave()
        }
        
        // DispatchGroup
        dispatchGroup.notify(queue: .main) {
            completion(mSeries, nil)
        }
    }
}
