//
//  MainPresenter.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 1/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func setupView()
    func presentSeries(response: Main.loadInitialData.Response)
}

class MainPresenter: MainPresentationLogic {
    
    weak var viewController: MainDisplayLogic?
    
    func setupView() {
        viewController?.setupView()
    }
    
    func presentSeries(response: Main.loadInitialData.Response) {
        
        // 1. save data in Manager
        SeriesManager.shared.setSeries(response.series ?? [])
        
        // 2. display data
        viewController?.displaySeries()
    }
}
