//
//  MainViewController.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 1/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainDelegate: class {
    func fetchedSeries(series: [Serie])
}

protocol MainDisplayLogic: class {
    func setupView()
    func displaySeries(viewModel: Main.loadInitialData.ViewModel)
}

class MainViewController: UITabBarController, MainDisplayLogic {
    
    var interactor: MainBusinessLogic?
    var router: (NSObjectProtocol & MainRoutingLogic & MainDataPassing)?
    weak var mainDelegate: MainDelegate?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = MainInteractor()
        let presenter = MainPresenter()
        let router = MainRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        interactor?.setupView()
    }
    
    // MARK: MainDisplayLogic
    
    func setupView() {
        print(#function)
    }
    
    func displaySeries(viewModel: Main.loadInitialData.ViewModel) {
        print(#function)
        
        let seriesVC = viewControllers?.getElement(0)?.children.getElement(0) as? SeriesViewController
        
        seriesVC?.interactor?.setSeries(viewModel.series ?? [])
        
        guard let delegate = mainDelegate else {
            print("mainDelegate is not initialized")
            return
        }
        
        delegate.fetchedSeries(series: viewModel.series ?? [])
    }
}
