//
//  MainInteractor.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 1/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func setupView()
    func getInitialData()
}

protocol MainDataStore {
}

class MainInteractor: MainBusinessLogic, MainDataStore {
    
    var presenter: MainPresentationLogic?
    var worker: MainWorker?
    
    func setupView() {
        worker = MainWorker()
        presenter?.setupView()
        getInitialData()
    }
    
    func getInitialData() {
        
        worker?.getInitialData(completion: { [weak self] (series, error) in
            
            guard error != nil else {
                
                // SUCCESS
                let response = Main.loadInitialData.Response(series: series)
                
                self?.presenter?.presentSeries(response: response)
                return
            }
            
            // FAILURE
            self?.presenter?.presentSeries(response: Main.loadInitialData.Response())
        })
    }
}
