//
//  MainPresenterTests.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 3/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONMarvelapp
import XCTest

class MainPresenterTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: MainPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupMainPresenter()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupMainPresenter() {
    sut = MainPresenter()
  }
  
  // MARK: Test doubles
  
    class MainDisplayLogicSpy: MainDisplayLogic {
        
        var setupViewCalled = false
        var displaySeriesCalled = false
        
        func setupView() {
            setupViewCalled = true
        }
        
        func displaySeries(viewModel: Main.loadInitialData.ViewModel) {
            displaySeriesCalled = true
        }
  }
  
  // MARK: Tests
  
    func testSetupView() {
        // Given
        let spy = MainDisplayLogicSpy()
        sut.viewController = spy
        
        // When
        sut.setupView()
        
        // Then
        XCTAssertTrue(spy.setupViewCalled, "setupView should ask the view controller to display the result")
    }
}
