//
//  SeriesPresenter.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 2/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SeriesPresentationLogic {
    func setupView(response: Series.SetupView.Response)
    func presentCharacters()
}

class SeriesPresenter: SeriesPresentationLogic {
    
    weak var viewController: SeriesDisplayLogic?
    
    func setupView(response: Series.SetupView.Response) {
        
        // 1. create viewModel
        let viewModel = Series.SetupView.ViewModel(title: response.title)
        
        // 2. display data
        viewController?.setupView(viewModel: viewModel)
    }
    
    func presentCharacters() {
        viewController?.displayCharacters()
    }
}
