//
//  SeriesRouter.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 2/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SeriesRoutingLogic {
    func routerToCharacters(segue: UIStoryboardSegue?)
}

protocol SeriesDataPassing {
    var dataStore: SeriesDataStore? { get }
}

class SeriesRouter: NSObject, SeriesRoutingLogic, SeriesDataPassing {
    
    weak var viewController: SeriesViewController?
    var dataStore: SeriesDataStore?
    
    func routerToCharacters(segue: UIStoryboardSegue?) {
        let storyboard = UIStoryboard(name: Constants.Storyboard.characters, bundle: nil)
        
        if let segue = segue, let destinationVC = segue.destination as? CharactersViewController {
            var destinationDS = destinationVC.router?.dataStore
            passDataToCharacters(source: dataStore, destination: &destinationDS)
        } else if let destinationVC = storyboard.instantiateInitialViewController() as? CharactersViewController {
            var destinationDS = destinationVC.router?.dataStore
            passDataToCharacters(source: dataStore, destination: &destinationDS)
            navigateToComments(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    fileprivate func navigateToComments(source: SeriesViewController, destination: CharactersViewController) {
        ui {
            source.navigationController?.pushViewController(destination, animated: true)
        }
    }
    
    // MARK: Passing data
    
    fileprivate func passDataToCharacters(source: SeriesDataStore?, destination: inout CharactersDataStore?) {
        destination?.serie = source?.selectedSerie
    }
}
