//
//  SeriesRouter.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 2/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SeriesRoutingLogic {
}

protocol SeriesDataPassing {
    var dataStore: SeriesDataStore? { get }
}

class SeriesRouter: NSObject, SeriesRoutingLogic, SeriesDataPassing {
    
    weak var viewController: SeriesViewController?
    var dataStore: SeriesDataStore?
}
