//
//  DetailsModels.swift
//  JSONMarvelapp
//
//  Created by Iván Díaz Molina on 3/12/20.
//  Copyright (c) 2020 IDIAZM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Details {
    // MARK: Use cases
    
    enum SetupView {
        struct Request {
        }
        struct Response {
            var character: Actor?
        }
        struct ViewModel {
            var characterName: String?
            var url: URL?
        }
    }
    
    enum Models {
        struct DetailCellModel {
            var serie: ResourceURI?
            var comic: ResourceURI?
            var type: TypeCell?
        }
        
        enum TypeCell {
            case serie
            case comic
        }
    }
}
